import React from 'react'
import { Icon } from '@mdi/react'
import * as mdiIcons from '@mdi/js'

// Mapeie os nomes dos ícones exatamente como estão no seu `iconMap` do Flutter
export const mdiIconMap: Record<string, string> = {
  food: mdiIcons.mdiFood,
  foodDrumstick: mdiIcons.mdiFoodDrumstick,
  foodSteak: mdiIcons.mdiFoodSteak,
  foodCroissant: mdiIcons.mdiFoodCroissant,
  foodTurkey: mdiIcons.mdiFoodTurkey,
  hamburger: mdiIcons.mdiHamburger,
  pizza: mdiIcons.mdiPizza,
  noodles: mdiIcons.mdiNoodles,
  frenchFries: mdiIcons.mdiFrenchFries,
  rice: mdiIcons.mdiRice,
  fish: mdiIcons.mdiFish,
  carrot: mdiIcons.mdiCarrot,
  corn: mdiIcons.mdiCorn,
  egg: mdiIcons.mdiEgg,
  apple: mdiIcons.mdiApple,
  foodOutline: mdiIcons.mdiFoodOutline,
  breadSlice: mdiIcons.mdiBreadSlice,
  baguette: mdiIcons.mdiBaguette,
  iceCream: mdiIcons.mdiIceCream,
  cupcake: mdiIcons.mdiCupcake,
  cookie: mdiIcons.mdiCookie,
  candy: mdiIcons.mdiCandy,
  sausage: mdiIcons.mdiSausage,
  mushroom: mdiIcons.mdiMushroom,
  peanut: mdiIcons.mdiPeanut,
  cheese: mdiIcons.mdiCheese,
  cornOff: mdiIcons.mdiCornOff,
  foodHotDog: mdiIcons.mdiFoodHotDog,
  foodForkDrink: mdiIcons.mdiFoodForkDrink,
  foodOff: mdiIcons.mdiFoodOff,
  foodVariant: mdiIcons.mdiFoodVariant,
  foodTakeoutBox: mdiIcons.mdiFoodTakeoutBox,
  turkey: mdiIcons.mdiTurkey,
  pasta: mdiIcons.mdiPasta,
  pretzel: mdiIcons.mdiPretzel,
  fruitCherries: mdiIcons.mdiFruitCherries,
  fruitPineapple: mdiIcons.mdiFruitPineapple,
  fruitWatermelon: mdiIcons.mdiFruitWatermelon,
  fruitGrapesOutline: mdiIcons.mdiFruitGrapesOutline,
  fruitPear: mdiIcons.mdiFruitPear,
  fruitCitrus: mdiIcons.mdiFruitCitrus,
  leaf: mdiIcons.mdiLeaf,
  pumpkin: mdiIcons.mdiPumpkin,
  seed: mdiIcons.mdiSeed,
  soySauce: mdiIcons.mdiSoySauce,
  spoonSugar: mdiIcons.mdiSpoonSugar,
  sprout: mdiIcons.mdiSprout,
  toaster: mdiIcons.mdiToaster,
  bottleTonic: mdiIcons.mdiBottleTonic,
  butterfly: mdiIcons.mdiButterfly,
  bowlMix: mdiIcons.mdiBowlMix,
  cake: mdiIcons.mdiCake,
  chefHat: mdiIcons.mdiChefHat,
  chiliMild: mdiIcons.mdiChiliMild,
  chiliHot: mdiIcons.mdiChiliHot,
  grill: mdiIcons.mdiGrill,
  knife: mdiIcons.mdiKnife,
  leafCircle: mdiIcons.mdiLeafCircle,
  mortarPestle: mdiIcons.mdiMortarPestle,
  potMix: mdiIcons.mdiPotMix,
  sausageOff: mdiIcons.mdiSausageOff,
  soySauceOff: mdiIcons.mdiSoySauceOff,
  stove: mdiIcons.mdiStove,
  tea: mdiIcons.mdiTea,
  hamburgerCheck: mdiIcons.mdiHamburgerCheck,
  hamburgerOff: mdiIcons.mdiHamburgerOff,
  fishOff: mdiIcons.mdiFishOff,
  tableFurniture: mdiIcons.mdiTableFurniture,
  toasterOff: mdiIcons.mdiToasterOff,
  bowl: mdiIcons.mdiBowl,
  glassCocktail: mdiIcons.mdiGlassCocktail,
  beer: mdiIcons.mdiBeer,
  glassMug: mdiIcons.mdiGlassMug,
  glassPintOutline: mdiIcons.mdiGlassPintOutline,
  bottleWine: mdiIcons.mdiBottleWine,
  bottleTonicPlus: mdiIcons.mdiBottleTonicPlus,
  bottleSoda: mdiIcons.mdiBottleSoda,
  bottleSodaClassic: mdiIcons.mdiBottleSodaClassic,
  bottleSodaOutline: mdiIcons.mdiBottleSodaOutline,
  cup: mdiIcons.mdiCup,
  coffee: mdiIcons.mdiCoffee,
  coffeeToGo: mdiIcons.mdiCoffeeToGo,
  teaOutline: mdiIcons.mdiTeaOutline,
  glassWine: mdiIcons.mdiGlassWine,
  glassTulip: mdiIcons.mdiGlassTulip,
  glassFlute: mdiIcons.mdiGlassFlute,
  glassCocktailOff: mdiIcons.mdiGlassCocktailOff,
  cupOff: mdiIcons.mdiCupOff,
  coffeeOff: mdiIcons.mdiCoffeeOff,
  glassStange: mdiIcons.mdiGlassStange,
  glassMugVariant: mdiIcons.mdiGlassMugVariant,
  glassMugVariantOff: mdiIcons.mdiGlassMugVariantOff,
  coffeeMaker: mdiIcons.mdiCoffeeMaker,
  coffeeToGoOutline: mdiIcons.mdiCoffeeToGoOutline,
  foodApple: mdiIcons.mdiFoodApple,
  silverwareForkKnife: mdiIcons.mdiSilverwareForkKnife,
  silverwareSpoon: mdiIcons.mdiSilverwareSpoon,
  silverwareVariant: mdiIcons.mdiSilverwareVariant,
  foodOffOutline: mdiIcons.mdiFoodOffOutline,
  foodAppleOutline: mdiIcons.mdiFoodAppleOutline,
  sproutOutline: mdiIcons.mdiSproutOutline, // Corrigido mdiSproutOutline para o nome correto do ícone
  seedOutline: mdiIcons.mdiSeedOutline,
  cart: mdiIcons.mdiCart,
  cartOutline: mdiIcons.mdiCartOutline,
  cartCheck: mdiIcons.mdiCartCheck,
  cartOff: mdiIcons.mdiCartOff,
  candyOutline: mdiIcons.mdiCandyOutline,
  cakeVariant: mdiIcons.mdiCakeVariant,
  cookieOutline: mdiIcons.mdiCookieOutline,
  cartRemove: mdiIcons.mdiCartRemove,
  microwave: mdiIcons.mdiMicrowave,
  basket: mdiIcons.mdiBasket,
  basketOutline: mdiIcons.mdiBasketOutline,
  basketFill: mdiIcons.mdiBasketFill,
  store: mdiIcons.mdiStore,
  storeOutline: mdiIcons.mdiStoreOutline,
  shoppingSearch: mdiIcons.mdiShoppingSearch,
  shopping: mdiIcons.mdiShopping,
  shoppingMusic: mdiIcons.mdiShoppingMusic,
}

export const getMdiReactIcon = (iconName: string, size: number = 1, color: string = 'currentColor') => {
  const path = mdiIconMap[iconName]
  if (!path) {
    // Retorna um ícone de erro ou um fallback, como um ? ou um ícone padrão
    console.warn(`Ícone não encontrado: ${iconName}`)
    return React.createElement(Icon, { path: mdiIcons.mdiAlertCircleOutline, size, color }); // Exemplo de fallback
  }
  return React.createElement(Icon, { path: path, size, color });
}
