import type { NovoPedidoContextValue } from './novoPedidoContextTypes'
import type { NovoPedidoFormContextValue } from './NovoPedidoFormContext'
import type { NovoPedidoDetalheSlice, NovoPedidoUISlice } from './novoPedidoContextTypes'

export function splitFormContextValue(
  value: NovoPedidoContextValue
): NovoPedidoFormContextValue {
  const {
    currentStep: _cs,
    empresa: _e,
    seletorClienteOpen: _sco,
    setSeletorClienteOpen: _ssco,
    tooltipGrupoId: _tg,
    setTooltipGrupoId: _stg,
    tooltipPosition: _tp,
    setTooltipPosition: _stp,
    modalEdicaoProdutoOpen: _meo,
    setModalEdicaoProdutoOpen: _smeo,
    modalLancamentoProdutoPainelOpen: _mlpo,
    setModalLancamentoProdutoPainelOpen: _smlpo,
    modalConfirmacaoSaidaOpen: _mcso,
    setModalConfirmacaoSaidaOpen: _smcso,
    modalCancelarVendaOpen: _mcvo,
    setModalCancelarVendaOpen: _smcvo,
    handleClose: _hc,
    handleConfirmarSaida: _hcs,
    handleCancelarSaida: _hcsa,
    gruposScrollRef: _gsr,
    meiosPagamentoScrollRef: _mpsr,
    isDragging: _id,
    isDraggingMeiosPagamento: _idmp,
    hasMovedRef: _hmr,
    hasMovedMeiosPagamentoRef: _hmmr,
    handleMouseDown: _hmd,
    handleMouseDownMeiosPagamento: _hmdmp,
    handleGruposWheel: _hgw,
    handleMouseMove: _hmm,
    handleMouseUp: _hmu,
    handleMouseLeave: _hml,
    longPressTimeoutRef: _lptr,
    longPressIndexRef: _lpir,
    longPressComplementoTimeoutRef: _lpctr,
    longPressComplementoIndexRef: _lpcir,
    modoVisualizacao: _mv,
    tabelaOrigemVenda: _tov,
    tipoInicioPedido: _tii,
    statusFiscalUnificado: _sfu,
    isLoadingVenda: _ilv,
    abaDetalhesPedido: _adp,
    detalhesPedidoMeta: _dpm,
    detalhesEntregaPedido: _dep,
    resumoFinanceiroDetalhes: _rfd,
    resumoFiscal: _rf,
    statusFiscalDetalhe: _sfd,
    podeExibirAbaNotaFiscal: _peanf,
    podeExibirAbaDadosEntrega: _peade,
    podeEditarPagamentoEntregaEmAberto: _pepeea,
    produtoTabsModalState: _ptms,
    handleAbrirEdicaoProdutoDetalhes: _haepd,
    handleFecharProdutoTabsModal: _hfptm,
    handleTabChangeProdutoModal: _htcpm,
    handleConfirmarCancelamentoVenda: _hccv,
    cancelarVendaGestor: _cvg,
    cancelarNotaFiscalVendaPdv: _cnfvp,
    cancelarNotaFiscalVendaGestor: _cnfvg,
    tipoCancelamentoSelecionado: _tcs,
    setTipoCancelamentoSelecionado: _stcs,
    justificativaCancelamento: _jc,
    setJustificativaCancelamento: _sjc,
    ...form
  } = value
  return form as NovoPedidoFormContextValue
}

export function splitUIContextValue(value: NovoPedidoContextValue): NovoPedidoUISlice {
  return {
    currentStep: value.currentStep,
    empresa: value.empresa,
    seletorClienteOpen: value.seletorClienteOpen,
    setSeletorClienteOpen: value.setSeletorClienteOpen,
    tooltipGrupoId: value.tooltipGrupoId,
    setTooltipGrupoId: value.setTooltipGrupoId,
    tooltipPosition: value.tooltipPosition,
    setTooltipPosition: value.setTooltipPosition,
    modalEdicaoProdutoOpen: value.modalEdicaoProdutoOpen,
    setModalEdicaoProdutoOpen: value.setModalEdicaoProdutoOpen,
    modalLancamentoProdutoPainelOpen: value.modalLancamentoProdutoPainelOpen,
    setModalLancamentoProdutoPainelOpen: value.setModalLancamentoProdutoPainelOpen,
    modalConfirmacaoSaidaOpen: value.modalConfirmacaoSaidaOpen,
    setModalConfirmacaoSaidaOpen: value.setModalConfirmacaoSaidaOpen,
    modalCancelarVendaOpen: value.modalCancelarVendaOpen,
    setModalCancelarVendaOpen: value.setModalCancelarVendaOpen,
    handleClose: value.handleClose,
    handleConfirmarSaida: value.handleConfirmarSaida,
    handleCancelarSaida: value.handleCancelarSaida,
    gruposScrollRef: value.gruposScrollRef,
    meiosPagamentoScrollRef: value.meiosPagamentoScrollRef,
    isDragging: value.isDragging,
    isDraggingMeiosPagamento: value.isDraggingMeiosPagamento,
    hasMovedRef: value.hasMovedRef,
    hasMovedMeiosPagamentoRef: value.hasMovedMeiosPagamentoRef,
    handleMouseDown: value.handleMouseDown,
    handleMouseDownMeiosPagamento: value.handleMouseDownMeiosPagamento,
    handleGruposWheel: value.handleGruposWheel,
    handleMouseMove: value.handleMouseMove,
    handleMouseUp: value.handleMouseUp,
    handleMouseLeave: value.handleMouseLeave,
    longPressTimeoutRef: value.longPressTimeoutRef,
    longPressIndexRef: value.longPressIndexRef,
    longPressComplementoTimeoutRef: value.longPressComplementoTimeoutRef,
    longPressComplementoIndexRef: value.longPressComplementoIndexRef,
  }
}

export function splitDetalheContextValue(
  value: NovoPedidoContextValue
): NovoPedidoDetalheSlice {
  return {
    modoVisualizacao: value.modoVisualizacao,
    tabelaOrigemVenda: value.tabelaOrigemVenda,
    tipoInicioPedido: value.tipoInicioPedido,
    statusFiscalUnificado: value.statusFiscalUnificado,
    isLoadingVenda: value.isLoadingVenda,
    abaDetalhesPedido: value.abaDetalhesPedido,
    detalhesPedidoMeta: value.detalhesPedidoMeta,
    detalhesEntregaPedido: value.detalhesEntregaPedido,
    resumoFinanceiroDetalhes: value.resumoFinanceiroDetalhes,
    resumoFiscal: value.resumoFiscal,
    statusFiscalDetalhe: value.statusFiscalDetalhe,
    podeExibirAbaNotaFiscal: value.podeExibirAbaNotaFiscal,
    podeExibirAbaDadosEntrega: value.podeExibirAbaDadosEntrega,
    podeEditarPagamentoEntregaEmAberto: value.podeEditarPagamentoEntregaEmAberto,
    produtoTabsModalState: value.produtoTabsModalState,
    handleAbrirEdicaoProdutoDetalhes: value.handleAbrirEdicaoProdutoDetalhes,
    handleFecharProdutoTabsModal: value.handleFecharProdutoTabsModal,
    handleTabChangeProdutoModal: value.handleTabChangeProdutoModal,
    handleConfirmarCancelamentoVenda: value.handleConfirmarCancelamentoVenda,
    cancelarVendaGestor: value.cancelarVendaGestor,
    cancelarNotaFiscalVendaPdv: value.cancelarNotaFiscalVendaPdv,
    cancelarNotaFiscalVendaGestor: value.cancelarNotaFiscalVendaGestor,
    tipoCancelamentoSelecionado: value.tipoCancelamentoSelecionado,
    setTipoCancelamentoSelecionado: value.setTipoCancelamentoSelecionado,
    justificativaCancelamento: value.justificativaCancelamento,
    setJustificativaCancelamento: value.setJustificativaCancelamento,
  }
}
